import Providers from '@/app/providers';
import { Navbar } from '@/components/layout/Navbar';
import { Inter } from 'next/font/google';
import './global.css';

export const metadata = {
  title: 'Welcome to storefront',
  description: 'Generated by create-nx-workspace',
};

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en" className={fontSans.variable}>
        <body>
          <Navbar></Navbar>
          {children}
        </body>
      </html>
    </Providers>
  );
}
