import './global.css';
import {Inter} from 'next/font/google'
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import Providers from "@/app/providers";

export const metadata = {
  title: 'Welcome to storefront',
  description: 'Generated by create-nx-workspace',
};

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {

  return (
    <Providers>
      <html lang="en" className={fontSans.variable}>
      <body>{children}</body>
      </html>
    </Providers>
  );
}
